name: ugyon
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  pinput: ^3.0.1 # Add this for OTP input
  google_fonts: ^6.1.0 # Use the latest version available
  cupertino_icons: ^1.0.8
  flutter_map: ^6.1.0
  latlong2: ^0.9.0 # For handling latitude/longitude
  geolocator: ^11.0.0 # For getting user's location
  firebase_core: ^2.27.2     # Core Firebase package
  firebase_auth: ^4.17.4      # Firebase Auth (example)
  cloud_firestore: ^4.15.3    # Firestore (example)
  firebase_storage: ^11.6.5   # Storage (optional)
  firebase_database: ^10.4.5
  qr_flutter: ^4.1.0 # For QR code generation
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ugyon_logo.png
    - assets/images/ugyon_screen_image.png
    - assets/images/ugyon_secondscreen_image.png
    - assets/images/ugyon_thirdscreen_image.png
    - assets/images/google_icon.png
    - assets/images/google_icon.svg
    - assets/images/slide1_ugyon.png
    - assets/images/slide2_jollibee.png
    - assets/images/slide3.png
    - assets/images/slide4.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
